import math
import glob
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from ScrewDriver.ScrewDriver import ModelScrewDriver
from StartDatasetBuild import main as buildDataset
from torch.optim.lr_scheduler import CosineAnnealingLR
from DataExtraction.BuildDataset import ScrewdriverDataset

torch.set_float32_matmul_precision('high')

class TrainingTools(nn.Module):
    
    def _directional_loss(self, pred, target):
        # Flatten matrices to vectors for similarity calculation
        p_flat = pred.view(pred.size(0), -1)
        t_flat = target.view(target.size(0), -1)
        
        mse = F.mse_loss(pred, target)
        
        # 1.0 - cos_sim gives us a value that is 0 when directions match perfectly
        cos_loss = 1.0 - F.cosine_similarity(p_flat, t_flat).mean()
        
        return mse + 0.5 * cos_loss
    
    
    def _extract_task_space_matrices(self, model, neutral_prompt, active_prompt, text_sample):
        """Extracts the 'Task Space' matrices A and B for a given text sample by comparing the neutral and active prompt states.

        Args:
            model (_type_): model to extract from (should be in eval mode and on the correct device)
            neutral_prompt (_type_): neutral prompt string that doesn't hint at the task
            active_prompt (_type_): task prompt string that explicitly states the task (e.g., "Analyze the sentiment of this text: [Text]")
            text_sample (_type_): the raw text sample to be analyzed

        Returns:
            Matrices A_large, B_large: The extracted Task Space matrices that represent the transformation from the neutral state to the active state for the given text sample.
        """
        
        # 1. Neutral: "The event occurred on a Tuesday afternoon. [Text]"
        # 2. Active: "Analyze the sentiment of this text: [Text]"
        
        # We reuse your existing logic but specifically for the Task-Neutral gap
        A_large, B_large, _ = self.extract_task_matrices(
            model, 
            [neutral_prompt + " " + text_sample], 
            [active_prompt + " " + text_sample], 
            is_small=False, 
            calc_variance=False
        )
        
        return A_large[0], B_large[0]
        
    def _orthogonal_penalty(self, A):
        """Addition to loss function by penalizing the lack of different directions, penalizing their cosine similarity,
        encouraging them to be orthogonal.

        Args:
            A (_type_): Raw weight matrix from the generator that we want to regularize for better generalization
            and to prevent collapse into a single direction.

        Returns:
            _type_: A scalar penalty value that can be added to the generator's loss to encourage the learned weight matrices to capture diverse directions in the Task Space,
            rather than collapsing into a single dominant direction.
        """
        B, L, R, D = A.shape
        if R <= 1: return torch.tensor(0.0, device=A.device)
        
        # ADDED: + 1e-6 prevents division by zero in float16 mixed precision
        A_norm = F.normalize(A + 1e-6, p=2, dim=-1) 
        sim_matrix = torch.matmul(A_norm, A_norm.mT)
        identity = self.base_identity.expand(B, L, R, R)
        
        return F.mse_loss(sim_matrix, identity)
    
    
    @torch.amp.autocast('cuda', enabled=False)
    def cyclic_trace(self, A_target, A_pred, B_target, B_pred):
        """Designed to find the Frobenius Norm of A, B from the generator using the Cyclic Property of the Trace, which allows us to compute ||P - T||^2 without ever explicitly computing P or T, thus saving memory and improving stability.

        Args:
            A_target (_type_): The 'A' matrix extracted from the Task Space using the oracle prompt, representing the ideal transformation for the task.
            A_pred (_type_): The 'A' matrix generated by the Screwdriver's generator head, which we want to train to match A_target.
            B_target (_type_): The 'B' matrix extracted from the Task Space using the oracle prompt, representing the ideal transformation for the task.
            B_pred (_type_): The 'B' matrix generated by the Screwdriver's generator head, which we want to train to match B_target.
        Returns:
            _type_: A scalar loss value representing the mean squared error between the predicted and target transformations in the Task Space, computed using the cyclic property of the trace to avoid explicit matrix reconstruction.
        """
        
        # 1. Force strictly fp32 to prevent Tensor Core overflow
        A_target, A_pred = A_target.float(), A_pred.float()
        B_target, B_pred = B_target.float(), B_pred.float()

        # 2. Compute traces
        inner_prod = (torch.matmul(A_target, A_pred.mT) * torch.matmul(B_pred.mT, B_target).mT).sum(dim=(-1, -2)) 
        norm_sq_P = (torch.matmul(A_pred, A_pred.mT) * torch.matmul(B_pred.mT, B_pred).mT).sum(dim=(-1, -2))
        norm_sq_T = (torch.matmul(A_target, A_target.mT) * torch.matmul(B_target.mT, B_target).mT).sum(dim=(-1, -2))

        # 3. ABSOLUTE DISTANCE (No more division)
        # This mathematically equates to ||P - T||^2
        raw_mse = norm_sq_P + norm_sq_T - 2 * inner_prod
        d_large = A_target.shape[-1]
        # raw_mse should never be negative, but floating point math is a lie.
        stable_mse = torch.clamp(raw_mse / d_large, min=1e-7).mean()
            
        # We drop the Cosine Loss entirely, as it causes gradient chaos at this scale.
        return stable_mse + 1e-6